### ISSUE TITLE
You probably want to install "only" ipykernel.

### ISSUE THREAD

**Issue by Carreau** [mapio/jupyter-virtualenv-osx#1]
You likely don't want to install `jupyter`, as this is the meta package that pulls everything. 
You likely want to install "only" ipykernel and issue a `python -m ipykernel install ... <options>`.

Thus the notebook server (and the rest) will be launch/loaded from_outside_ of the venv, and the kernel and the rest will be ran from inside the venv.

Which is in most case what users are trying to do.

**Comment by mapio** [comment]
Actually (as the `README.md` and repo name and description suggest) this is not the case. I am firmly convinced that installing additional packages directly in the system package directory is a bad idea.

Nonetheless, given that some user may want to do what you suggest, and the script can be adapted also tu such case, I've made it usable also for such case.
