### ISSUE TITLE
Documentation for running this with (ana)conda installation of python 2.7

### ISSUE THREAD

**Issue by emirkmo** [mapio/jupyter-virtualenv-osx#4]
A standard way to use (ana)conda is to simply have it as your default way of running python with the packages you want, and just knowing that it gives you the option to create other virtual envs if necessary, even though this option might not really be used.

So for many conda users for which this is the case: where they simply run conda to install a standardized installation of python with some common libraries, and use whatever python + packages it installed as a default, and always work within this virtual env by default, how can one run this script? In this scenario, one wants to set it so that the matplotlib installation that comes with the standard python 2.7 conda installation works with Jupyter notebooks using the macosx backend every time.

Put another way, can you describe how I would get this script running with a default 2.7 conda installation, and start Jupyter notebook?

**Comment by mapio** [comment]
I'm sorry, I don't use or know nothing about Conda. 

The point of this script is to create a *kernel configuration* file with an environment setting `PYTHONHOME` to the value of the environment variable `VIRTUAL_ENV` that is the path where virtualenv puts its Python executable.

I guess that Conda follows a similar approach, setting up a particular Python executable, or environment. To use this same approach with Conda will probably boil down to setting `PYTHONHOME`  in the *kernel configuration* file to reflect the Conda setup.
